/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-10-21 05:03:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1603256501005L));
    _jspx_dependants.put("/admin_header.jsp", Long.valueOf(1603256486182L));
    _jspx_dependants.put("/admin_footer.jsp", Long.valueOf(1603256486132L));
    _jspx_dependants.put("jar:file:/D:/웹개발학원/11애플리케이션테스트수행_과제/wp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/wp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/D:/웹개발학원/11애플리케이션테스트수행_과제/wp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/wp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("utf-8"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>LINE FRIENDS</title>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/ad.css\">    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	session.setAttribute("id", "admin");

      out.write('\r');
      out.write('\n');

	if(session.getAttribute("id") != "admin") {

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\talert(\"관리자로 하지 않으셨습니다. 현재 페이지는 관리자의 로그인이 필요합니다.\");\r\n");
      out.write("\thistory.go(-1);\r\n");
      out.write("</script>\r\n");
 	
	} else {

      out.write('\r');
      out.write('\n');
		
	}

      out.write("\r\n");
      out.write("    <div class=\"wrap\">   \r\n");
      out.write("        <header class=\"hd\">\r\n");
      out.write("            <nav class=\"gnb\">\r\n");
      out.write("               <ul class=\"gnb_top\">                   \r\n");
      out.write("\t               <li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"index.jsp\" class=\"logo\" ><img src=\"./img/img_logo2.png\" alt=\"logo\"></a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"logout_btn\">\t\r\n");
      out.write("\t\t\t\t\t\t<a href=\"admin.jsp\" ><img src=\"./img/icon_logout.png\">LOGOUT</a>\t\t\t\t         \r\n");
      out.write("\t               </li>                   \r\n");
      out.write("               </ul>\r\n");
      out.write("               <ul class=\"gnb_lst\">                   \r\n");
      out.write("                   <li><a href=\"\">회원관리</a></li>\r\n");
      out.write("                   <li><a href=\"\">게시판관리</a></li>\r\n");
      out.write("                   <li><a href=\"\">판매관리</a></li>\r\n");
      out.write("                   <li><a href=\"\">상품관리</a></li>\r\n");
      out.write("                   <li><a href=\"\">구매관리</a></li>\r\n");
      out.write("                   <li><a href=\"\">고객문자발송</a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>");
      out.write(" <!-- 관리자 페이지 헤더 모듈화 -->\r\n");
      out.write("        <main class=\"content\">\t\t\t\r\n");
      out.write("\t\t\t<section class=\"page\" id=\"page1\">\r\n");
      out.write("\t\t\t\t<h2 class=\"page_tit\">회원 관리 메뉴</h2>\r\n");
      out.write("\t\t\t\t<nav class=\"menu\">\r\n");
      out.write("                    <ul class=\"mem_con\">\r\n");
      out.write("                        <li><a href=\"mem_list.jsp\">회원 목록 보기</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"mem_search.jsp\">회원 검색</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"mem_ins.jsp\">회원 등록</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"mem_del.jsp\">회원 삭제</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"mem_upd.jsp\">회원정보 수정</a></li>\t\t\t\t\t\t\r\n");
      out.write("                    </ul>\r\n");
      out.write("\t\t\t\t\t<!-- <ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"memberList.jsp\">회원관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"admBoardList.jsp\">게시판관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"salesList.jsp\">판매관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"productList.jsp\">상품관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"curtList.jsp\">구매관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"sendSms.jsp\">고객문자발송</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"admin_edit.jsp\">관리자 정보 수정</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"protocol_edit.jsp\">회원약관 수정</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"privacy_edit.jsp\">개인정보처리방침 수정</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"company_edit.jsp\">회사정보 수정</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"product_edit.jsp\">상품정보 수정</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"order_edit.jsp\">주문정보 수정</a></li>\r\n");
      out.write("\t\t\t\t\t</ul> -->\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("            </section>        \r\n");
      out.write("\t\t</main>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"ft\">\r\n");
      out.write("            <h2>\r\n");
      out.write("                <a href=\"\" class=\"ft_logo\">\r\n");
      out.write("                    <img src=\"./img/footer_logo.png\" alt=\"ft_logo\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </h2>\r\n");
      out.write("            <div class=\"txt\">\r\n");
      out.write("                <ul class=\"ft_menu\">\r\n");
      out.write("                    <li><a href=\"\">제휴제안</a></li>\r\n");
      out.write("                    <li><a href=\"\">온라인 스토어</a></li>\r\n");
      out.write("                    <li><a href=\"\">개인정보 처리방침</a></li>\r\n");
      out.write("                    <li><a href=\"\">FRIENDS CARE</a></li>                    \r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"info\">\r\n");
      out.write("                    <ul class=\"info1\">\r\n");
      out.write("                        <li>라인프렌즈 주식회사&nbsp;</li>\r\n");
      out.write("                        <li>사업자등록번호 : 726-87-00030&nbsp;</li>\r\n");
      out.write("                        <li>통신판매업 신고번호 : 2015-경기성남-0597&nbsp;</li>                   \r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <ul class=\"info1\">\r\n");
      out.write("                        <li>대표이사 : 김성훈&nbsp;</li>\r\n");
      out.write("                        <li>서울특별시 용산구 한남대로 98, 5층 라인프렌즈&nbsp;</li>\r\n");
      out.write("                        <li>1544-5921</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <address>Copyright © SKY.J All Rights Reserved</address>\r\n");
      out.write("            </div>           \r\n");
      out.write("        </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write(" <!-- 관리자 페이지 푸터 모듈화 -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
